### PR TITLE
Fixes react examples

### LINKED ISSUE #9: Catch  and Release fails when there is a new feature
If there is a new feature, and the  client is in C&R mode, this specific condition  causes an exception in the client.

### PR DESCRIPTION
**Pull request by rvowles**
This also addresses a edge case with catch & release.

Fixes #9

### CODE REVIEW

File: examples/todo-backend-typescript/run.sh [hunk 1]
```diff
@@ -1,5 +1,6 @@
 #!/bin/sh
 export FEATUREHUB_ACCEPT_BAGGAGE=true
-export FEATUREHUB_EDGE_URL=http://localhost:8085/
-export FEATUREHUB_CLIENT_API_KEY=default/6a3ec2bc-e061-4d52-a4d2-0f80e1a40543/hnfsr2tGKDXmZx58Y1LIw8MeblAObr*fMFq4YJ3xj9aKVSGEk7h
+export FEATUREHUB_CLIENT_API_KEY=default/bf05d5c7-b494-4df1-a0f2-7a66967b7bcf/7tNxYCY7VB10gp5SzJLQwzzlNHTdRw*3AjdbcU1zI8OZebj1DIn
+export FEATUREHUB_EDGE_URL=http://localhost:8085
+export FEATUREHUB_BASE_URL=http://localhost:8085
```
Comment (IrinaSouth) [inline examples/todo-backend-typescript/run.sh:5]: edge and base the same?

File: featurehub-javascript-client-sdk/app/client_feature_repository.ts [hunk 2]
```diff
@@ -246,8 +246,8 @@ export class ClientFeatureRepository implements InternalFeatureRepository {
     if (features && features.length > 0) {
       features.forEach((f) => {
         const existingFeature = this.features.get(f.key);
-        if (!existingFeature || (existingFeature.getKey()
-          && f.version > existingFeature.getFeatureState().version)) {
+        if (!existingFeature || !existingFeature.exists || (existingFeature.getKey()
```
Comment (IrinaSouth) [inline featurehub-javascript-client-sdk/app/client_feature_repository.ts:249]: how can it be !existingFeature.exists if this.feature.get(f.key) has returned something?

File: examples/todo-backend-typescript/run.sh (hunk 1 above)
Comment (rvowles) [reply examples/todo-backend-typescript/run.sh:5]: shouldn't have been included. It is the  same here because its party-server.

File: featurehub-javascript-client-sdk/app/client_feature_repository.ts (hunk 2 above)
Comment (rvowles) [reply featurehub-javascript-client-sdk/app/client_feature_repository.ts:249]: because you added a listener before your key existed. So  it always creates a FeatureBaseHolder to hold your listener and when the feature turns  up, it passes that state onto the real feature. So the feature is in the map, but doesn't actually exist in the backend list of features.

**Review by IrinaSouth — APPROVED** [review]
